server:
  id: 1
  type: ${SERVER_TYPE:prod}

admin:
  id: ${SERVER_ADMIN_ID:123456789}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/couple}
    username: ${SPRING_DATASOURCE_USERNAME:happy}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${RESTART:none}
      auto_quote_keyword: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET:AGVeqC3DaElzFlY3JKdEtlYLJldEtMNOeBNlY3JldEtleQ==}

crypto:
  secret-key: ${CRYPTO_SECRET_KEY:12345678901234567890123456789012}
  init-vector: ${CRYPTO_INIT_VECTOR:babyTest12345678}
